"""
P5 — Multi-Cloud Egress Optimizer | Streamlit Dashboard
Mirrors the CLI dashboard exactly, adding live charts and interactive results.

Run: streamlit run streamlit_app.py
"""

import sys
import os
import time

# Add project root so src/ imports work
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import streamlit as st
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="P5 — Multi-Cloud Egress Optimizer",
    page_icon="☁️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ── Custom CSS ────────────────────────────────────────────────────────────────
st.markdown("""
<style>
  /* Dark themed metric cards */
  [data-testid="stMetric"] {
      background: #161b22;
      border: 1px solid #30363d;
      border-radius: 10px;
      padding: 16px;
  }
  [data-testid="stMetricValue"] { color: #58a6ff !important; font-size: 2rem !important; }
  [data-testid="stMetricLabel"] { color: #8b949e !important; }
  /* Sidebar styling */
  section[data-testid="stSidebar"] { background: #0d1117; border-right: 1px solid #30363d; }
  /* Code blocks */
  code { color: #d2a8ff; }
  /* Make dataframe headers accent colored */
  thead tr th { color: #58a6ff !important; }
</style>
""", unsafe_allow_html=True)

# ── Import project modules ────────────────────────────────────────────────────
@st.cache_resource(show_spinner="Loading pricing data...")
def load_pricing():
    from src.pricing.unified_model import PricingModel
    return PricingModel()

@st.cache_resource(show_spinner="Loading topologies...")
def load_topologies():
    from src.topology import get_all_topologies
    return get_all_topologies()

pricing = load_pricing()
topologies = load_topologies()
topo_map = {t.name: t for t in topologies}

# ── Sidebar Navigation ────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## ☁️ P5 Optimizer")
    st.markdown("*Multi-Cloud Egress-Aware Placement*")
    st.divider()

    page = st.radio(
        "Navigation",
        [
            "🏠 Overview & Figures",
            "📊 Algorithm Comparison",
            "🗺️ Placement Decisions",
            "📈 Live Parameter Sweep",
            "🔬 Ablation Study",
            "💱 Egress Rate Matrix",
            "⚖️ CodeCourt Case Study",
            "🗄️ Pricing Explorer",
        ],
        label_visibility="collapsed",
    )

    st.divider()
    st.caption("**GitHub:**")
    st.caption("[multicloud_egress_optimizer](https://github.com/AtharvSinha26052005/multicloud_egress_optimizer)")
    st.caption("Review 2 — September 2026")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 0 — OVERVIEW & FIGURES
# ═══════════════════════════════════════════════════════════════════════════════
if page == "🏠 Overview & Figures":
    st.markdown("# ☁️ Multi-Cloud Egress Optimizer")
    st.markdown("### Egress-aware placement using **TEAP** — a novel 5-phase hybrid algorithm")
    st.markdown("> *Greedy cloud cost calculators show you the cheapest VM — but ignore data transfer costs between services. TEAP finds placements that minimize both compute AND egress.*")

    # Key metrics
    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Max Savings vs Greedy", "43.9%", "at 10x traffic")
    c2.metric("Experiments Run", "120", "5 topologies × 4 traffic × 6 algos")
    c3.metric("Algorithms", "6", "Greedy, ILP, SA, TEAP...")
    c4.metric("CodeCourt Annual Savings", "$948", "at 5x traffic")

    st.divider()

    # --- Review 1 baseline table ---
    st.subheader("📋 Review 1 Baseline — Validated Numbers")
    st.caption("These exact numbers must be reproduced by every algorithm. TEAP matches the optimal every time.")
    r1_data = {
        "Placement": ["Greedy (GCP+GCP+Azure)", "Optimal (All-GCP)", "All-AWS", "All-Azure", "Worst (GCP+Azure+AWS)"],
        "Web": ["GCP", "GCP", "AWS", "Azure", "GCP"],
        "App": ["GCP", "GCP", "AWS", "Azure", "Azure"],
        "DB": ["Azure", "GCP", "AWS", "Azure", "AWS"],
        "Compute ($)": [279.54, 284.50, 335.80, 302.88, 318.63],
        "Egress ($)": [24.87, 1.20, 0.90, 0.87, 78.30],
        "Total ($)": [304.41, 285.70, 336.70, 303.75, 396.93],
    }
    df_r1 = pd.DataFrame(r1_data)
    st.dataframe(df_r1, use_container_width=True, hide_index=True)

    st.divider()

    # --- 6 Figures ---
    st.subheader("📊 Generated Figures")
    st.caption("All generated by `python generate_figures.py`. Hover to zoom.")

    fig_dir = os.path.join(os.path.dirname(__file__), "results", "figures")

    figures = [
        ("fig1_cost_by_algorithm.png", "Fig 1 — Cost by Algorithm", "Bar chart: all 6 algorithms across 5 topologies. Greedy always pays more egress than the optimal alternatives."),
        ("fig2_cost_vs_traffic.png", "Fig 2 — Cost vs Traffic Volume", "**Key graph**: Greedy cost grows steeply while TEAP/ILP stay near-flat. Red shaded area = egress penalty. Gap crosses 15% at 2.5x traffic."),
        ("fig3_runtime_comparison.png", "Fig 3 — Solver Runtime", "Greedy ≈ 0ms (too fast, ignores egress), ILP = 47-800ms, TEAP = ~160ms. SA is fastest heuristic after Greedy."),
        ("fig4_ablation.png", "Fig 4 — Ablation Study", "Removing ILP refinement on Microservice Mesh causes cost to jump 31.9%. ILP Phase 4 is the critical component."),
        ("fig5_egress_heatmap.png", "Fig 5 — Egress Rate Heatmap", "3×3 matrix. Diagonal = FREE. GCP row = most expensive ($0.12/GB). Azure row = cheapest ($0.087/GB). Phase 3 exploits this."),
        ("fig6_codecourt_case.png", "Fig 6 — CodeCourt Case Study", "Left: cost comparison. Right: savings from 3.1% → 17.2%. Dashed line = 15% hypothesis threshold, crossed at 5x traffic."),
    ]

    for i in range(0, 6, 2):
        col1, col2 = st.columns(2)
        for col, (fname, title, caption) in zip([col1, col2], figures[i:i+2]):
            with col:
                img_path = os.path.join(fig_dir, fname)
                if os.path.exists(img_path):
                    st.image(img_path, caption=f"**{title}**", use_container_width=True)
                    st.caption(caption)
                else:
                    st.warning(f"Run `python generate_figures.py` to generate {fname}")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 1 — ALGORITHM COMPARISON
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "📊 Algorithm Comparison":
    st.markdown("# 📊 Algorithm Comparison")
    st.markdown("*Run all 6 algorithms on any topology and traffic level. Mirrors CLI option [1].*")

    col1, col2 = st.columns(2)
    with col1:
        selected_topo_name = st.selectbox("Select Topology", list(topo_map.keys()))
    with col2:
        traffic_mult = st.slider("Traffic Multiplier", 0.5, 10.0, 1.0, 0.5)

    topology = topo_map[selected_topo_name]
    scaled = topology.scale_traffic(traffic_mult) if traffic_mult != 1.0 else topology

    if st.button("▶ Run All Algorithms", type="primary", use_container_width=True):
        from src.algorithms.greedy import GreedySolver
        from src.algorithms.single_provider import SingleProviderSolver
        from src.algorithms.exhaustive import ExhaustiveSolver
        from src.algorithms.ilp_solver import ILPSolver
        from src.algorithms.simulated_annealing import SASolver
        from src.algorithms.teap import TEAPSolver

        solvers = [
            GreedySolver(), SingleProviderSolver(), ExhaustiveSolver(),
            ILPSolver(), SASolver(), TEAPSolver(),
        ]

        results = []
        progress = st.progress(0, text="Running algorithms...")
        for i, solver in enumerate(solvers):
            t0 = time.perf_counter()
            result = solver.solve(scaled, pricing)
            elapsed = time.perf_counter() - t0
            results.append({
                "Algorithm": result.solver_name,
                "Compute ($)": round(result.cost.compute, 2),
                "Egress ($)": round(result.cost.egress, 2),
                "Total ($)": round(result.cost.total, 2),
                "Runtime (ms)": round(elapsed * 1000, 1),
                "Placement": str(result.placement),
            })
            progress.progress((i + 1) / len(solvers), text=f"Done: {solver.name}")

        progress.empty()

        df = pd.DataFrame(results)
        optimal = df["Total ($)"].min()
        df["vs Optimal (%)"] = ((df["Total ($)"] - optimal) / optimal * 100).round(1)

        st.success(f"Completed! Optimal cost: **${optimal:.2f}**")

        # Highlighted table
        def highlight_rows(row):
            if row["vs Optimal (%)"] == 0.0:
                return ["background-color: #1a3a1a; color: #3fb950"] * len(row)
            elif row["vs Optimal (%)"] > 10:
                return ["background-color: #3a1a1a; color: #f78166"] * len(row)
            return [""] * len(row)

        display_df = df.drop(columns=["Placement"])
        st.dataframe(
            display_df.style.apply(highlight_rows, axis=1),
            use_container_width=True, hide_index=True
        )

        # Bar chart
        fig, axes = plt.subplots(1, 2, figsize=(12, 4))
        fig.patch.set_facecolor("#0d1117")
        for ax in axes:
            ax.set_facecolor("#161b22")

        colors = ["#e74c3c", "#3498db", "#2ecc71", "#9b59b6", "#f39c12", "#1abc9c"]
        algorithms = df["Algorithm"].tolist()

        axes[0].bar(algorithms, df["Compute ($)"], color=colors, alpha=0.7)
        axes[0].set_title("Compute Cost", color="white")
        axes[0].set_xticklabels(algorithms, rotation=20, ha="right", color="white", fontsize=8)
        axes[0].set_ylabel("$/month", color="white")
        axes[0].tick_params(colors="white")

        axes[1].bar(algorithms, df["Total ($)"], color=colors, alpha=0.9)
        axes[1].axhline(optimal, color="#3fb950", linestyle="--", linewidth=1.5, label=f"Optimal ${optimal:.2f}")
        axes[1].set_title("Total Cost (Compute + Egress)", color="white")
        axes[1].set_xticklabels(algorithms, rotation=20, ha="right", color="white", fontsize=8)
        axes[1].set_ylabel("$/month", color="white")
        axes[1].tick_params(colors="white")
        axes[1].legend(facecolor="#161b22", labelcolor="white")

        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        # Placement details
        with st.expander("🗺️ Placement Details (which component → which cloud)"):
            for r in results:
                placement = eval(r["Placement"]) if isinstance(r["Placement"], str) else r["Placement"]
                st.markdown(f"**{r['Algorithm']}** — Total: ${r['Total ($)']:.2f}")
                p_df = pd.DataFrame([{"Component": k, "Provider": v} for k, v in placement.items()])
                st.dataframe(p_df, use_container_width=True, hide_index=True)
    else:
        st.info("Select a topology and traffic multiplier, then click Run.")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 2 — PLACEMENT DECISIONS
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "🗺️ Placement Decisions":
    st.markdown("# 🗺️ Placement Decisions")
    st.markdown("*See exactly which component goes to which cloud. Mirrors CLI option [2].*")

    selected_topo_name = st.selectbox("Select Topology", list(topo_map.keys()))
    topology = topo_map[selected_topo_name]

    if st.button("▶ Show Placements", type="primary", use_container_width=True):
        from src.algorithms.greedy import GreedySolver
        from src.algorithms.teap import TEAPSolver
        from src.algorithms.ilp_solver import ILPSolver

        col1, col2, col3 = st.columns(3)
        for col, (name, solver) in zip([col1, col2, col3], [
            ("Greedy", GreedySolver()),
            ("TEAP", TEAPSolver()),
            ("ILP", ILPSolver()),
        ]):
            result = solver.solve(topology, pricing)
            rows = []
            for comp in topology.components:
                prov = result.placement[comp.name]
                compute = pricing.get_compute_cost(comp.component_type, prov)
                instance = pricing.get_instance_name(comp.component_type, prov)
                rows.append({
                    "Component": comp.name,
                    "Provider": prov,
                    "Instance": instance,
                    "$/month": f"${compute:.2f}",
                })

            with col:
                status = "🟢" if result.cost.total == min(result.cost.total, result.cost.total) else "🔴"
                st.markdown(f"### {name}")
                st.metric("Total", f"${result.cost.total:.2f}",
                          delta=f"Egress: ${result.cost.egress:.2f}")
                st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)

        # Traffic matrix
        st.subheader("📡 Traffic Matrix")
        st.caption(f"Data flows in {topology.name}")
        traffic_rows = []
        for (src, dst), vol in topology.traffic_matrix.items():
            traffic_rows.append({"Source": src, "Destination": dst, "Traffic (GB/mo)": vol})
        st.dataframe(pd.DataFrame(traffic_rows), use_container_width=True, hide_index=True)

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 3 — LIVE PARAMETER SWEEP
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "📈 Live Parameter Sweep":
    st.markdown("# 📈 Live Parameter Sweep")
    st.markdown("*Watch the cost gap between Greedy and TEAP grow as traffic increases. Mirrors CLI option [3].*")

    col1, col2 = st.columns(2)
    with col1:
        selected_topo_name = st.selectbox("Topology", list(topo_map.keys()))
    with col2:
        max_mult = st.slider("Max Traffic Multiplier", 2.0, 15.0, 10.0, 0.5)

    topology = topo_map[selected_topo_name]

    if st.button("▶ Run Live Sweep", type="primary", use_container_width=True):
        from src.algorithms.greedy import GreedySolver
        from src.algorithms.teap import TEAPSolver
        from src.algorithms.ilp_solver import ILPSolver

        multipliers = list(np.arange(0.5, max_mult + 0.01, 0.5))

        greedy_costs, teap_costs, ilp_costs, gaps = [], [], [], []

        progress = st.progress(0, text="Sweeping...")
        table_placeholder = st.empty()
        chart_placeholder = st.empty()

        g_solver = GreedySolver()
        t_solver = TEAPSolver()
        i_solver = ILPSolver()

        rows_so_far = []
        for idx, mult in enumerate(multipliers):
            scaled = topology.scale_traffic(mult)
            g = g_solver.solve(scaled, pricing)
            t = t_solver.solve(scaled, pricing)
            i = i_solver.solve(scaled, pricing)

            greedy_costs.append(g.cost.total)
            teap_costs.append(t.cost.total)
            ilp_costs.append(i.cost.total)
            gap = (g.cost.total - t.cost.total) / g.cost.total * 100
            gaps.append(round(gap, 1))

            rows_so_far.append({
                "Traffic": f"{mult:.1f}x",
                "Greedy ($)": f"${g.cost.total:.2f}",
                "ILP ($)": f"${i.cost.total:.2f}",
                "TEAP ($)": f"${t.cost.total:.2f}",
                "Gap %": f"{gap:.1f}%",
                "Status": "✅ >15%" if gap >= 15 else ("⚠️" if gap >= 10 else ""),
            })

            # Update table
            table_placeholder.dataframe(pd.DataFrame(rows_so_far), use_container_width=True, hide_index=True)

            # Update chart
            fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 4))
            fig.patch.set_facecolor("#0d1117")
            for ax in [ax1, ax2]:
                ax.set_facecolor("#161b22")
                ax.tick_params(colors="white")
                ax.spines["bottom"].set_color("#30363d")
                ax.spines["left"].set_color("#30363d")
                ax.spines["top"].set_color("#30363d")
                ax.spines["right"].set_color("#30363d")

            mults_so_far = multipliers[:idx + 1]

            ax1.plot(mults_so_far, greedy_costs, "o-", color="#e74c3c", linewidth=2, label="Greedy")
            ax1.plot(mults_so_far, ilp_costs, "s-", color="#3498db", linewidth=2, label="ILP")
            ax1.plot(mults_so_far, teap_costs, "^-", color="#2ecc71", linewidth=2, label="TEAP")
            ax1.fill_between(mults_so_far, greedy_costs, teap_costs, alpha=0.15, color="#e74c3c")
            ax1.set_xlabel("Traffic Multiplier", color="white")
            ax1.set_ylabel("$/month", color="white")
            ax1.set_title("Cost vs Traffic", color="white")
            ax1.legend(facecolor="#161b22", labelcolor="white")
            ax1.yaxis.label.set_color("white")

            ax2.bar(mults_so_far, gaps, color=["#e74c3c" if g >= 15 else "#f39c12" if g >= 10 else "#3498db" for g in gaps])
            ax2.axhline(15, color="#3fb950", linestyle="--", linewidth=1.5, label="15% threshold")
            ax2.set_xlabel("Traffic Multiplier", color="white")
            ax2.set_ylabel("Gap (%)", color="white")
            ax2.set_title("Greedy vs TEAP Gap %", color="white")
            ax2.legend(facecolor="#161b22", labelcolor="white")

            plt.tight_layout()
            chart_placeholder.pyplot(fig)
            plt.close()
            progress.progress((idx + 1) / len(multipliers), text=f"Traffic: {mult:.1f}x | Gap: {gap:.1f}%")

        progress.empty()

        # Find crossover
        crossover = next((m for m, g in zip(multipliers, gaps) if g >= 15), None)
        if crossover:
            st.success(f"✅ **15% hypothesis threshold crossed at {crossover:.1f}x traffic!**")
        else:
            st.info(f"15% threshold not reached in this sweep range (max gap: {max(gaps):.1f}%)")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 4 — ABLATION STUDY
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "🔬 Ablation Study":
    st.markdown("# 🔬 Ablation Study")
    st.markdown("*Which TEAP phase contributes most? Mirrors CLI option [4].*")
    st.info("We disable one TEAP phase at a time and measure the cost impact.")

    col1, col2 = st.columns(2)
    with col1:
        selected_topo_name = st.selectbox("Select Topology", list(topo_map.keys()))
    with col2:
        traffic_mult = st.slider("Traffic Multiplier", 0.5, 10.0, 3.5, 0.5)

    topology = topo_map[selected_topo_name]
    scaled = topology.scale_traffic(traffic_mult) if traffic_mult != 1.0 else topology

    if st.button("▶ Run Ablation Study", type="primary", use_container_width=True):
        from src.algorithms.greedy import GreedySolver
        from src.algorithms.teap import TEAPSolver

        variants = [
            ("Greedy (baseline)", GreedySolver()),
            ("TEAP — Full (all phases)", TEAPSolver(use_clustering=True, use_asymmetry=True, use_ilp_refinement=True)),
            ("TEAP — No Clustering", TEAPSolver(use_clustering=False, use_asymmetry=True, use_ilp_refinement=True)),
            ("TEAP — No Asymmetry", TEAPSolver(use_clustering=True, use_asymmetry=False, use_ilp_refinement=True)),
            ("TEAP — No ILP Refine", TEAPSolver(use_clustering=True, use_asymmetry=True, use_ilp_refinement=False)),
        ]

        rows = []
        for name, solver in variants:
            result = solver.solve(scaled, pricing)
            rows.append({
                "Variant": name,
                "Compute ($)": round(result.cost.compute, 2),
                "Egress ($)": round(result.cost.egress, 2),
                "Total ($)": round(result.cost.total, 2),
            })

        df = pd.DataFrame(rows)
        optimal = df["Total ($)"].min()
        df["vs Best (%)"] = ((df["Total ($)"] - optimal) / optimal * 100).round(1)

        st.dataframe(df, use_container_width=True, hide_index=True)

        # Bar chart
        fig, ax = plt.subplots(figsize=(10, 4))
        fig.patch.set_facecolor("#0d1117")
        ax.set_facecolor("#161b22")
        colors = ["#95a5a6", "#2ecc71", "#e74c3c", "#f39c12", "#9b59b6"]
        bars = ax.bar(df["Variant"], df["Total ($)"], color=colors, alpha=0.85)
        ax.axhline(df[df["Variant"].str.contains("Full")]["Total ($)"].values[0],
                   color="#3fb950", linestyle="--", linewidth=1.5, label="TEAP Full")
        for bar, val in zip(bars, df["Total ($)"]):
            ax.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 1,
                    f"${val:.0f}", ha="center", color="white", fontsize=9)
        ax.set_xticklabels(df["Variant"], rotation=15, ha="right", color="white", fontsize=9)
        ax.set_ylabel("$/month", color="white")
        ax.set_title(f"TEAP Ablation — {topology.name} (traffic ×{traffic_mult})", color="white")
        ax.tick_params(colors="white")
        ax.legend(facecolor="#161b22", labelcolor="white")
        plt.tight_layout()
        st.pyplot(fig)
        plt.close()

        greedy_cost = df[df["Variant"] == "Greedy (baseline)"]["Total ($)"].values[0]
        teap_cost = df[df["Variant"].str.contains("Full")]["Total ($)"].values[0]
        savings = greedy_cost - teap_cost
        if savings > 0:
            st.success(f"**TEAP-Full saves ${savings:.2f}/mo ({savings/greedy_cost*100:.1f}%) over Greedy** at {traffic_mult}x traffic")
        else:
            st.info("Same cost — this topology favors single-provider placement at this traffic level.")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 5 — EGRESS RATE MATRIX
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "💱 Egress Rate Matrix":
    st.markdown("# 💱 Egress Rate Matrix")
    st.markdown("*Why direction matters — the core insight of TEAP Phase 3. Mirrors CLI option [5].*")

    from src.pricing.fallback_data import EGRESS_RATES, PROVIDERS

    providers = PROVIDERS
    matrix_data = {}
    for src in providers:
        row = {}
        for dst in providers:
            rate = EGRESS_RATES.get((src, dst), 0)
            row[f"→ {dst}"] = rate
        matrix_data[src] = row

    df_egress = pd.DataFrame(matrix_data).T
    df_egress.index.name = "From \\ To"

    st.subheader("Egress Rate Table ($/GB)")
    st.dataframe(df_egress.style.format("${:.3f}").background_gradient(cmap="Reds"), use_container_width=True)

    # Show the stored heatmap figure
    fig_path = os.path.join(os.path.dirname(__file__), "results", "figures", "fig5_egress_heatmap.png")
    if os.path.exists(fig_path):
        st.image(fig_path, caption="Egress Rate Heatmap — GCP row is most expensive", use_container_width=True)

    st.divider()
    col1, col2, col3 = st.columns(3)
    col1.metric("GCP Egress Rate", "$0.120/GB", "Most expensive", delta_color="inverse")
    col2.metric("AWS Egress Rate", "$0.090/GB", "Mid-range", delta_color="off")
    col3.metric("Azure Egress Rate", "$0.087/GB", "Cheapest", delta_color="normal")

    st.subheader("💡 Worked Example — Why This Matters")
    traffic_gb = st.slider("Traffic volume (GB/month)", 100, 2000, 500, 50)

    c1, c2, c3 = st.columns(3)
    c1.metric(f"If {traffic_gb}GB sent from GCP", f"${traffic_gb * 0.12:.2f}", "$0.12/GB")
    c2.metric(f"If {traffic_gb}GB sent from AWS", f"${traffic_gb * 0.09:.2f}", "$0.09/GB")
    c3.metric(f"If {traffic_gb}GB sent from Azure", f"${traffic_gb * 0.087:.2f}", "$0.087/GB")
    saving = traffic_gb * (0.12 - 0.087)
    st.success(f"**Saving ${saving:.2f}/month ({saving/(traffic_gb*0.12)*100:.0f}%)** by swapping the sender from GCP to Azure — same data, same volume, just smarter placement. TEAP does this automatically in Phase 3.")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 6 — CODECOURT CASE STUDY
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "⚖️ CodeCourt Case Study":
    st.markdown("# ⚖️ CodeCourt Case Study")
    st.markdown("*Your actual project — Nginx → API Server → Redis → Judge Workers → PostgreSQL. Mirrors CLI option [6].*")

    from src.topology.codecourt import create_codecourt_topology
    from src.algorithms.greedy import GreedySolver
    from src.algorithms.teap import TEAPSolver

    topology = create_codecourt_topology()

    # Show architecture
    st.subheader("Architecture")
    arch_rows = []
    for comp in topology.components:
        arch_rows.append({"Component": comp.name, "Role": comp.description, "vCPU": comp.vcpu, "RAM (GB)": comp.ram_gb})
    st.dataframe(pd.DataFrame(arch_rows), use_container_width=True, hide_index=True)

    # Traffic matrix
    with st.expander("📡 Traffic Matrix"):
        t_rows = [{"Source": s, "Destination": d, "Traffic (GB/mo)": v} for (s, d), v in topology.traffic_matrix.items()]
        st.dataframe(pd.DataFrame(t_rows), use_container_width=True, hide_index=True)

    st.divider()

    # Run comparison
    if st.button("▶ Run Greedy vs TEAP Comparison", type="primary", use_container_width=True):
        traffic_levels = [1.0, 2.0, 3.5, 5.0]
        summary_rows = []

        col1, col2 = st.columns(2)
        with col1:
            st.markdown("### 🔴 Greedy Placement (baseline traffic)")
            g_base = GreedySolver().solve(topology, pricing)
            greedy_rows = []
            for comp in topology.components:
                prov = g_base.placement[comp.name]
                cost = pricing.get_compute_cost(comp.component_type, prov)
                greedy_rows.append({"Component": comp.name, "Provider": prov, "$/month": f"${cost:.2f}"})
            st.dataframe(pd.DataFrame(greedy_rows), use_container_width=True, hide_index=True)
            st.metric("Compute", f"${g_base.cost.compute:.2f}")
            st.metric("Egress", f"${g_base.cost.egress:.2f}", delta="cross-cloud penalty", delta_color="inverse")
            st.metric("Total", f"${g_base.cost.total:.2f}")

        with col2:
            st.markdown("### 🟢 TEAP Placement (optimized)")
            t_base = TEAPSolver().solve(topology, pricing)
            teap_rows = []
            for comp in topology.components:
                prov = t_base.placement[comp.name]
                cost = pricing.get_compute_cost(comp.component_type, prov)
                teap_rows.append({"Component": comp.name, "Provider": prov, "$/month": f"${cost:.2f}"})
            st.dataframe(pd.DataFrame(teap_rows), use_container_width=True, hide_index=True)
            st.metric("Compute", f"${t_base.cost.compute:.2f}")
            st.metric("Egress", f"${t_base.cost.egress:.2f}", delta="co-located savings", delta_color="normal")
            st.metric("Total", f"${t_base.cost.total:.2f}")

        # Cost vs traffic
        st.subheader("📈 Cost vs Traffic Level")
        g_costs, t_costs, savings_list = [], [], []
        for mult in traffic_levels:
            scaled = topology.scale_traffic(mult)
            g = GreedySolver().solve(scaled, pricing)
            t = TEAPSolver().solve(scaled, pricing)
            g_costs.append(g.cost.total)
            t_costs.append(t.cost.total)
            s = g.cost.total - t.cost.total
            savings_list.append(s)
            summary_rows.append({
                "Traffic": f"{mult}x",
                "Greedy ($)": f"${g.cost.total:.2f}",
                "TEAP ($)": f"${t.cost.total:.2f}",
                "Savings/month": f"${s:.2f}",
                "Savings %": f"{s/g.cost.total*100:.1f}%",
                "Annual Savings": f"${s*12:.0f}",
            })

        st.dataframe(pd.DataFrame(summary_rows), use_container_width=True, hide_index=True)

        # Show pre-generated figure
        fig_path = os.path.join(os.path.dirname(__file__), "results", "figures", "fig6_codecourt_case.png")
        if os.path.exists(fig_path):
            st.image(fig_path, caption="CodeCourt Case Study — Savings growing from 3.1% to 17.2%", use_container_width=True)

        # Annual savings highlight
        max_savings = max(savings_list)
        st.success(f"🎯 **At 5x traffic: TEAP saves ${max_savings:.2f}/month = ${max_savings*12:.0f}/year annually** — crossing the 15% research hypothesis threshold!")

# ═══════════════════════════════════════════════════════════════════════════════
# PAGE 7 — PRICING EXPLORER
# ═══════════════════════════════════════════════════════════════════════════════
elif page == "🗄️ Pricing Explorer":
    st.markdown("# 🗄️ Pricing Explorer")
    st.markdown("*Browse compute prices across AWS, GCP, and Azure. Mirrors CLI option [8].*")

    from src.pricing.fallback_data import COMPUTE_CATALOG

    component_types = list(COMPUTE_CATALOG.keys())
    selected_type = st.selectbox("Select Component Type", component_types)

    rows = []
    for provider in pricing.providers:
        info = COMPUTE_CATALOG[selected_type][provider]
        rows.append({
            "Provider": provider,
            "Instance": info["instance"],
            "vCPU": info["vcpu"],
            "RAM (GB)": info["ram_gb"],
            "$/month": info["price_monthly"],
        })

    df = pd.DataFrame(rows)
    cheapest = df.loc[df["$/month"].idxmin(), "Provider"]
    most_exp = df.loc[df["$/month"].idxmax(), "Provider"]

    c1, c2, c3 = st.columns(3)
    for col, prov in zip([c1, c2, c3], pricing.providers):
        row = df[df["Provider"] == prov].iloc[0]
        tag = " 💚 cheapest" if prov == cheapest else (" 🔴 most expensive" if prov == most_exp else "")
        col.metric(f"{prov}{tag}", f"${row['$/month']:.2f}/mo", row["Instance"])

    st.divider()
    st.dataframe(
        df.style.format({"$/month": "${:.2f}"}),
        use_container_width=True, hide_index=True
    )

    # Compare all component types
    st.subheader("Compare All Component Types")
    all_rows = []
    for ct in component_types:
        for prov in pricing.providers:
            all_rows.append({
                "Component Type": ct,
                "Provider": prov,
                "$/month": COMPUTE_CATALOG[ct][prov]["price_monthly"],
                "Instance": COMPUTE_CATALOG[ct][prov]["instance"],
            })

    df_all = pd.DataFrame(all_rows)
    pivot = df_all.pivot(index="Component Type", columns="Provider", values="$/month")

    fig, ax = plt.subplots(figsize=(10, 5))
    fig.patch.set_facecolor("#0d1117")
    ax.set_facecolor("#161b22")

    x = np.arange(len(pivot.index))
    width = 0.25
    colors = {"AWS": "#e74c3c", "GCP": "#3498db", "Azure": "#2ecc71"}
    for i, prov in enumerate(pricing.providers):
        ax.bar(x + i * width, pivot[prov], width, label=prov, color=colors[prov], alpha=0.85)

    ax.set_xticks(x + width)
    ax.set_xticklabels(pivot.index, rotation=25, ha="right", color="white", fontsize=9)
    ax.set_ylabel("$/month", color="white")
    ax.set_title("Compute Prices by Component Type and Provider", color="white")
    ax.legend(facecolor="#161b22", labelcolor="white")
    ax.tick_params(colors="white")
    plt.tight_layout()
    st.pyplot(fig)
    plt.close()
